FROM webdevops/php-nginx-dev:7.4

RUN wget -O/etc/apt/trusted.gpg.d/nginx.asc https://nginx.org/keys/nginx_signing.key && \
    printf "deb http://deb.debian.org/debian bullseye main contrib non-free\ndeb http://nginx.org/packages/debian/ bullseye nginx" > /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y default-jre libreoffice-java-common libreoffice-writer && \
    apt-get clean

